### PR TITLE
Extend support for schemas with `multipart/form-data` content

### PR DESCRIPTION
**Pull request by alexmalus**
Added `Reynard::Context#multipart_form` so consumers can pass form data to upload files.

### CODE REVIEW

**Comment by alexmalus** [comment]
@Manfred is this something you can find time to review please?

**Comment by Manfred** [comment]
Thanks for suggesting this, but I can't accept this PR. Params should be automatically serialized as multipart form data when the requested content type in the spec is `multipart/form-data`. Sort of similar to how we would support XML and form URL encoded if we supported that.

Implementation-wise I would expect `Specification#build_body` to return a subclass of serialized body that is specific to the  specced request body. Probably with some sort of registration class that allows you do hook in additional serializers.

**Comment by alexmalus** [comment]
Thanks for looking into this!

> I can't accept this PR [..]

No worries, I didn't expect an all-or-nothing response. My team uses Reynard across several applications, and since we now need to send files following an OpenAPI specification, we'd like to continue using Reynard for this task if possible.
Please answer some questions that can help me address some of the concerns you're having.

> Params should be automatically serialized as multipart form data when the requested content type in the spec is multipart/form-data

I'd like to clarify the API Reynard offer to consumers for the use case this PR tries to address. When you say "params", do you mean the existing API should be reused, like so?

```ruby
response = reynard.
  operation('createBookCover').
  params('size' => 'preview', 'subject' => 'In a Nutshell', 'attachment' => attachment').
  execute
```

> I would expect Specification#build_body to return a subclass of serialized body that is specific to the specced request body.

With the assumption that `Reynard::Context#params` will be used to register the information, are you then expecting this method to be extended in a similar way as `Reynard::Context#body` is constructed, building a serialized body that you mention and expect?

> Probably with some sort of registration class that allows you do hook in additional serializers

Where would you expect the registration class to be? Do you have an example that I can follow?

**Comment by alexmalus** [comment]
No worries, I appreciate the timely and sincere responses.
Closing the PR since it's not mergeable in this state.

**Pull request closed without merging**
